In [4]:
#Libraries, loop, lists 
import numpy as np 
import pandas as pd 


ModuleNotFoundError: No module named 'pandas'

In [2]:
pip install numpy

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5.4/5.4 MB 4.4 MB/s eta 0:00:00a 0:00:01m
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.

[notice] A new release of pip is available: 24.0 -> 26.2.1
[notice] To update, run: python3 -m pip install --upgrade pip
Note: you may need to restart the kernel to use updated packages.


In [5]:
import numpy as np 
import pandas as pd 

ModuleNotFoundError: No module named 'pandas'

In [6]:
pip install pandas


     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 79.5/79.5 kB 590.6 kB/s eta 0:00:00a 0:00:01
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 10.1/10.1 MB 7.4 MB/s eta 0:00:0000:010:01m

[notice] A new release of pip is available: 24.0 -> 26.2.1
[notice] To update, run: python3 -m pip install --upgrade pip
Note: you may need to restart the kernel to use updated packages.


In [ ]:
#Libraries, loop, lists 
#import two standard libs 
import numpy as np 
import pandas as pd 


In [13]:
#initialize an array 
#make an array of nums from 0-100
random_list = np.arange(stop=100)
#consult doc for further funcs - google search numpy . arange basically 


In [14]:
print(random_list)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]


In [16]:
#A1 use np.arange to create a new list, called even_list_1 that contains all the even numbers from 0 to 100 (exclusive).
even_list_1 = np.arange(0, 100, 2)
print(even_list_1)


[ 0  2  4  6  8 10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46
 48 50 52 54 56 58 60 62 64 66 68 70 72 74 76 78 80 82 84 86 88 90 92 94
 96 98]


In [26]:
#the bracket [] allows us to access a specific element in the list.
print(even_list_1[0]) #prints the first element in the list

#use the : to access elements accross a certain range 
print(even_list_1[5:15]) #prints the first 10 elements in the list

#: can also be used to access elements from the beginning or end of a list.
print(random_list[:5]) #prints the first 5 elements in the list
print(random_list[90 :]) #prints the last 10 elements in the list

0
[10 12 14 16 18 20 22 24 26 28]
[0 1 2 3 4]
[90 91 92 93 94 95 96 97 98 99]


In [31]:
#A2 

#print the element at the 90th index 
print(random_list[90])
#ninety_index = random_list[90] 
#good practice to not put numericals in variable names - write out ninety

#print the elements from index 10 to index 21
print(random_list[10:22])

#print the last 10 elemeents of the array 
print(random_list[-10:])

90
[10 11 12 13 14 15 16 17 18 19 20 21]
[90 91 92 93 94 95 96 97 98 99]


In [32]:
#doing maf operations on the list 
#want the list to start at 1 instead of 0 
random_list = random_list + 1
#if u run this a lot then it would keep adding 1 - make you actually want to reassign variable 
#add 1 to all elements in the list
print(random_list)

[  1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17  18
  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35  36
  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53  54
  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71  72
  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89  90
  91  92  93  94  95  96  97  98  99 100]


In [34]:
#boolean indexing can also be performed element-wise in an array 
#boolean index array that shows where all the odds(FALSE) are: 
print(random_list % 2== 0)

even_list_2 = random_list[random_list%2==0]
print(even_list_2)

[False  True False  True False  True False  True False  True False  True
 False  True False  True False  True False  True False  True False  True
 False  True False  True False  True False  True False  True False  True
 False  True False  True False  True False  True False  True False  True
 False  True False  True False  True False  True False  True False  True
 False  True False  True False  True False  True False  True False  True
 False  True False  True False  True False  True False  True False  True
 False  True False  True False  True False  True False  True False  True
 False  True False  True]
[  2   4   6   8  10  12  14  16  18  20  22  24  26  28  30  32  34  36
  38  40  42  44  46  48  50  52  54  56  58  60  62  64  66  68  70  72
  74  76  78  80  82  84  86  88  90  92  94  96  98 100]


In [36]:
#initialize an empty array 
even_list_3 = np.array([])
#for i in range just means for each value i 

for i in range(0,101):
    #check is the value i is even
    if i % 2 ==0:
        #use the np.append i since it's even 
        even_list_3 = np.append(arr=even_list_3, values= i)
print(even_list_3)

[  0.   2.   4.   6.   8.  10.  12.  14.  16.  18.  20.  22.  24.  26.
  28.  30.  32.  34.  36.  38.  40.  42.  44.  46.  48.  50.  52.  54.
  56.  58.  60.  62.  64.  66.  68.  70.  72.  74.  76.  78.  80.  82.
  84.  86.  88.  90.  92.  94.  96.  98. 100.]


In [ ]:
#make an array of nums 0-200 (exclusive) 
big_list = np. arange(200)

#multiply numbers resulting in a list 
even_list_4 = [2*x for x in big_list if x<=50]

even_list_4 = np.array(even_list_4)
print(even_list_4)

#these all show that there are different methods to get the same result - just depends on what you want to do and how you want to do it


[  0   2   4   6   8  10  12  14  16  18  20  22  24  26  28  30  32  34
  36  38  40  42  44  46  48  50  52  54  56  58  60  62  64  66  68  70
  72  74  76  78  80  82  84  86  88  90  92  94  96  98 100]


In [ ]:
#A3 
#A3  - from workbook1 your code here
test_list = np.array([ -99.52287875, -100.        ,  -99.39794001, -100.        ,
        -99.30103   ,  -99.04575749,  -99.69897   ,  -99.22184875,
        -99.30103   ,  -99.52287875,  -99.30103   ,  -99.09691001,
        -99.04575749,  -99.15490196,  -99.04575749,  -99.52287875,
        -99.69897   ,  -99.52287875,  -99.09691001,  -99.39794001,
        -99.22184875,  -99.69897   ,  -99.22184875,  -99.39794001])

#1. Add 100 to each number in the list
test_list = test_list + 100

 #2. Use [np.power()](https://numpy.org/doc/2.1/reference/generated/numpy.power.html) to take 10 to the power of each value in `test_list` (i.e. set 10 as the base and each value in `test_list` as the exponent)
test_list = np.power(10, test_list) #array wise operations so for loop unnecessary 

 #3. Use [np.round()](https://numpy.org/doc/2.1/reference/generated/numpy.round.html) to round each of the values in the list to the nearest whole number
test_list = np.round(test_list)

 #4. Print the first 5 elements of the list
print(test_list[:5])




[3. 1. 4. 1. 5.]


In [ ]:
#II. Dataframes and Pandas 
gapminder = pd.read_csv('data/gapminder.csv')
#importing a data set into a pandas dataframe
gapminder




,country,continent,year,lifeExp,pop,gdpPercap
0,Afghanistan,Asia,1952,28.801,8425333,779.445314
1,Afghanistan,Asia,1957,30.332,9240934,820.853030
2,Afghanistan,Asia,1962,31.997,10267083,853.100710
3,Afghanistan,Asia,1967,34.020,11537966,836.197138
4,Afghanistan,Asia,1972,36.088,13079460,739.981106
...,...,...,...,...,...,...
1699,Zimbabwe,Africa,1987,62.351,9216418,706.157306
1700,Zimbabwe,Africa,1992,60.377,10704340,693.420786
1701,Zimbabwe,Africa,1997,46.809,11404948,792.449960
1702,Zimbabwe,Africa,2002,39.989,11926563,672.038623


In [43]:
#this prints the data in the row at index number 1 - pandas has specific ways to do this 
print(gapminder.iloc[1])

country      Afghanistan
continent           Asia
year                1957
lifeExp           30.332
pop              9240934
gdpPercap      820.85303
Name: 1, dtype: object


In [44]:
#since the index (the 0th column in our dataframe is also integers, this also workds w .loc)
print(gapminder.loc[1])

country      Afghanistan
continent           Asia
year                1957
lifeExp           30.332
pop              9240934
gdpPercap      820.85303
Name: 1, dtype: object


In [45]:
#can also print the data in the first 5 rows 
print(gapminder.head(5))

       country continent  year  lifeExp       pop   gdpPercap
0  Afghanistan      Asia  1952   28.801   8425333  779.445314
1  Afghanistan      Asia  1957   30.332   9240934  820.853030
2  Afghanistan      Asia  1962   31.997  10267083  853.100710
3  Afghanistan      Asia  1967   34.020  11537966  836.197138
4  Afghanistan      Asia  1972   36.088  13079460  739.981106


In [46]:
#print using iloc 
print(gapminder.iloc[0:5])

       country continent  year  lifeExp       pop   gdpPercap
0  Afghanistan      Asia  1952   28.801   8425333  779.445314
1  Afghanistan      Asia  1957   30.332   9240934  820.853030
2  Afghanistan      Asia  1962   31.997  10267083  853.100710
3  Afghanistan      Asia  1967   34.020  11537966  836.197138
4  Afghanistan      Asia  1972   36.088  13079460  739.981106


In [48]:
#print specific columns: print the data in the column continent 
print(gapminder.loc[:,'continent'])

0         Asia
1         Asia
2         Asia
3         Asia
4         Asia
         ...  
1699    Africa
1700    Africa
1701    Africa
1702    Africa
1703    Africa
Name: continent, Length: 1704, dtype: str


In [ ]:

print(gapminder[['continent', 'country']])

     continent      country
0         Asia  Afghanistan
1         Asia  Afghanistan
2         Asia  Afghanistan
3         Asia  Afghanistan
4         Asia  Afghanistan
...        ...          ...
1699    Africa     Zimbabwe
1700    Africa     Zimbabwe
1701    Africa     Zimbabwe
1702    Africa     Zimbabwe
1703    Africa     Zimbabwe

[1704 rows x 2 columns]
